use_frameworks!

target 'RxBehaviorTester_Example' do
  pod 'RxSwift', '~> 4.0'
  pod 'RxBlocking', '~> 4.0'
  pod 'RxBehaviorTester', :path => '../'

  target 'RxBehaviorTester_Tests' do
    inherit! :search_paths

    pod 'Nimble', '~> 7.0.2'
  end
end
